### ISSUE TITLE
manager.py should not use hardcoded 'id'

### ISSUE THREAD

**Issue by marcofalcioni** [M1hacka/django-pg-returning#16]
line 42 and 172 should use 'pk' instead of 'id' I think. I am trying to verify this. I'll post updates when I do.

**Comment by M1ha-Shvn** [comment]
Hi, thanks for reporting.
I suppose, you are right, but it's a little bit more complex. ReturningQuerySet gets data with native database column names. Its `values_list` method is not django one, it doesn't know, what field is a primary key. So what can be done is:
1) Fetching `pk` name from django model in manager.py and getting it instead of `id`
2) Resolving column names like `pk` inside ReturningQuerySet based on it's model and replacing `id` to `pk` in manager.py.

To my mind second way is more pretty.

I'm sorry, but I have no time for fixing it this week. I'll have a look in 2-3 weeks. If you want it faster - please, make a PR and I'll accept it.

**Comment by M1ha-Shvn** [comment]
Released [1.2.2](https://github.com/M1hacka/django-pg-returning/releases/tag/v1.2.2)
